name: navigator_comparison
description: A project to compare vrouter vs go_router
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6595
  vrouter: ^1.2.1
  go_router: ^4.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  flutter_markdown: ^0.6.10+3
  markdown: ^5.0.0 # the same version at flutter_markdown

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/